export default {
  fields2: [
    {
      id: 'id',
      description: 'ID',
      show: false,
    },
    {
      id: 'first_name',
      description: 'First Name',
      show: true,
    },
    {
      id: 'last_name',
      description: 'Last Name',
      show: true,
    },
    {
      id: 'email',
      description: 'E-mail',
      show: true,
    },
    {
      id: 'company',
      description: 'Company',
      show: true,
    },
    {
      id: 'ip_address',
      description: 'IP Address',
      show: true,
    },
    {
      id: 'country_code',
      description: 'Country',
      show: true,
    },
  ],
  fields: [
    {
      id: 'id',
      description: 'ID',
      show: false,
    },
    {
      id: 'country',
      description: 'Country',
      show: true,
    },
    {
      id: 'joined',
      show: true,
      description: 'joined',
    },
    {id: 'balance', show: true, description: 'balance'},
    {id: 'annual_fee', show: true, description: 'annual_fee'},
    {id: 'address_1', show: true, description: 'address_1'},
    {id: 'start', show: true, description: 'start'},
    {id: 'dues', show: true, description: 'dues'},
    {id: 'annual_billing', show: true, description: 'annual_billing'},
    {id: 'address2', show: true, description: 'address2'},
    {id: 'renewal', show: true, description: 'renewal'},
    {id: 'term_ends', show: true, description: 'term_ends'},
    {id: 'city_state_zip', show: true, description: 'city_state_zip'},
    {id: 'expires', show: true, description: 'expires'},
    {id: 'initiation', show: true, description: 'initiation'},
    {id: 'training_total', show: true, description: 'training_total'},
    {id: 'country', show: true, description: 'country'},
    {id: 'joined', show: true, description: 'joined'},
    {id: 'balance', show: true, description: 'balance'},
    {id: 'home_phone', show: true, description: 'home_phone'},
    {id: 'access', show: true, description: 'access'},
    {id: 'first_last', show: true, description: 'first_last'},
    {id: 'sessions', show: true, description: 'sessions'},
    {id: 'cell_phone', show: true, description: 'cell_phone'},
    {id: 'home_club', show: true, description: 'home_club'},
    {id: '6 MO. VIP', show: true, description: '6 MO. VIP'},
    {id: 'tl_sessions', show: true, description: 'tl_sessions'},
    {id: 'emg_phone', show: true, description: 'emg_phone'},
    {id: 'e_contact', show: true, description: 'e_contact'},
    {id: 'rate_id', show: true, description: 'rate_id'},
    {id: 'phone_barcode', show: true, description: 'phone_barcode'},
    {
      id: 'last_name',
      description: 'last_name',
      show: true,
    },
    {
      id: 'email',
      description: 'E-mail',
      show: true,
    },
    {
      id: 'company',
      description: 'Company',
      show: true,
    },
    {
      id: 'ip_address',
      description: 'IP Address',
      show: true,
    },
    {
      id: 'country_code',
      description: 'Country',
      show: true,
    },
  ],
  items: [
    {
      id: 1,
      country: 'United States',
      joined: '11/29/2021',
      balance: '0.00',
      annual_fee: '49.00',
      address_1: '123 EverStreet Trace',
      start: '11/29/2021',
      dues: '29.99',
      annual_billing: '12/29/2022',
      address2: 'N/A',
      renewal: '0.00',
      term_ends: 'N/A',
      city_state_zip: 'Carmel, IN 46203',
      expires: 'None',
      initiation: '0.00',
      training_total: 'N/A',
      country: 'United States',
      joined: '11/29/2021',
      balance: '0.00',
      home_phone: 'N/A',
      access: 'Multi Club',
      first_last: '59.98',
      sessions: 'N/A',
      cell_phone: '3172504880',
      home_club: 'WESTFIELD - 146TH ST',
      '6 MO. VIP': 'None',
      tl_sessions: 'N/A',
      emg_phone: 'N/A',
      e_contact: 'N/A',
      rate_id: '1142843',
      phone_barcode: true,
    },
  ],
  third: [
    {
      id: 1,
      service: 'fitness',
      dues: 0,
      freeze: 0,
    },
    {
      id: 2,
      service: 'guest priviledges',
      dues: 0,
      freeze: 0,
    },
    {id: 3, service: 'multistate', dues: 0, freeze: 0},
    {id: 4, service: 'group fitness', dues: 0, freeze: 0},
    {
      id: 5,
      service: 'pool whirlpool spa',
      dues: 0,
      freeze: 0,
    },
    {
      id: 6,
      service: 'cycle class',
      dues: 0,
      freeze: 0,
    },
    {id: 7, service: 'la fitness access', dues: 0, freeze: 0},
    {
      id: 8,
      service: 'esporta access',
      dues: 0,
      freeze: 0,
    },
  ],
  items2: [
    {
      id: 1,
      first_name: 'Matias',
      last_name: 'Gauntlett',
      email: 'mgauntlett0@mapquest.com',
      company: 'Fivespan',
      ip_address: '39.139.197.152',
      country_code: 'CN',
    },
    {
      id: 2,
      first_name: 'Laney',
      last_name: 'Veque',
      email: 'lveque1@census.gov',
      company: 'Aimbu',
      ip_address: '77.0.37.83',
      country_code: 'ZM',
    },
    {
      id: 3,
      first_name: 'Fielding',
      last_name: 'Donson',
      email: 'fdonson2@indiatimes.com',
      company: 'Meevee',
      ip_address: '141.126.205.140',
      country_code: 'ID',
    },
    {
      id: 4,
      first_name: 'Ferdinand',
      last_name: 'Bessent',
      email: 'fbessent3@chronoengine.com',
      company: 'Riffpath',
      ip_address: '65.217.64.181',
      country_code: 'FR',
    },
    {
      id: 5,
      first_name: 'Nels',
      last_name: 'Tilt',
      email: 'ntilt4@last.fm',
      company: 'Flashset',
      ip_address: '68.194.140.19',
      country_code: 'JP',
    },
    {
      id: 6,
      first_name: 'Jen',
      last_name: 'Sterrie',
      email: 'jsterrie5@reference.com',
      company: 'Youbridge',
      ip_address: '210.173.199.119',
      country_code: 'VE',
    },
    {
      id: 7,
      first_name: 'Lindsy',
      last_name: 'Kelway',
      email: 'lkelway6@jimdo.com',
      company: 'Rhyloo',
      ip_address: '138.154.16.188',
      country_code: 'CN',
    },
    {
      id: 8,
      first_name: 'Stacy',
      last_name: 'Graeber',
      email: 'sgraeber7@exblog.jp',
      company: 'Dazzlesphere',
      ip_address: '167.47.78.169',
      country_code: 'PH',
    },
    {
      id: 9,
      first_name: 'Sharon',
      last_name: 'Stainland',
      email: 'sstainland8@devhub.com',
      company: 'Browsebug',
      ip_address: '63.59.239.96',
      country_code: 'CN',
    },
    {
      id: 10,
      first_name: 'Caldwell',
      last_name: 'Rimell',
      email: 'crimell9@hexun.com',
      company: 'Rhynyx',
      ip_address: '12.81.190.233',
      country_code: 'PL',
    },
  ],
};
