export default {
  user_field: [
    {
      id: 'first_name',
      description: 'First Name',
      show: true,
    },
    {
      id: 'last_name',
      description: 'Last Name',
      show: true,
    },

    {
      id: 'barcode',
      description: 'Barcode',
      show: true,
    },
    {
      id: 'status',
      description: 'Status',
      show: true,
    },
  ],
  user_item: [
    {
      last_name: 'Disney',
      first_name: 'Walt',
      status: 'OK',
      barcode: 'FFFFFFFF',
    },
  ],
  fields2: [
    {
      id: 'id',
      description: 'ID',
      show: false,
    },
    {
      id: 'first_name',
      description: 'First Name',
      show: true,
    },
    {
      id: 'last_name',
      description: 'Last Name',
      show: true,
    },
    {
      id: 'email',
      description: 'E-mail',
      show: true,
    },
    {
      id: 'company',
      description: 'Company',
      show: true,
    },
    {
      id: 'ip_address',
      description: 'IP Address',
      show: true,
    },
    {
      id: 'country_code',
      description: 'Country',
      show: true,
    },
  ],
  fields: [
    {
      id: 'id',
      description: 'ID',
      show: false,
    },
    {
      id: 'country',
      description: 'Country',
      show: true,
    },
    {
      id: 'joined',
      show: true,
      description: 'Joined',
    },
    {id: 'balance', show: true, description: 'Balance'},
    {id: 'annual_fee', show: true, description: 'Annual Fee'},
    {id: 'address_1', show: true, description: 'Address1'},
    {id: 'start', show: true, description: 'Start'},
    {id: 'dues', show: true, description: 'Dues'},
    {id: 'annual_billing', show: true, description: 'Annual Billing'},
    {id: 'address2', show: true, description: 'Address2'},
    {id: 'renewal', show: true, description: 'Renewal'},
    {id: 'term_ends', show: true, description: 'Term Ends'},
    {id: 'city_state_zip', show: true, description: 'City/State/Zip'},
    {id: 'expires', show: true, description: 'Expires'},
    {id: 'initiation', show: true, description: 'Initiation'},
    {id: 'training_total', show: true, description: 'Training Total'},
    {id: 'country', show: true, description: 'Country'},
    {id: 'joined', show: true, description: 'Joined'},
    {id: 'balance', show: true, description: 'Balance'},
    {id: 'home_phone', show: true, description: 'Home Phone'},
    {id: 'access', show: true, description: 'Access'},
    {id: 'first_last', show: true, description: 'First Last'},
    {id: 'sessions', show: true, description: 'Sessions'},
    {id: 'cell_phone', show: true, description: 'Cell Phone'},
    {id: 'home_club', show: true, description: 'Home Club'},
    {id: '6 MO. VIP', show: true, description: '6 MO. VIP'},
    {id: 'tl_sessions', show: true, description: 'Tl Sessions'},
    {id: 'emg_phone', show: true, description: 'Emg Phone'},
    {id: 'e_contact', show: true, description: 'E. Contact'},
    {id: 'rate_id', show: true, description: 'Rate Id'},
    {id: 'phone_barcode', show: true, description: 'Phone Barcode'},
    {
      id: 'last_name',
      description: 'Last Name',
      show: true,
    },
  ],
  items: [
    {
      id: 1,
      country: 'United States',
      joined: '11/29/2021',
      balance: '0.00',
      annual_fee: '49.00',
      address_1: '123 EverStreet Trace',
      start: '11/29/2021',
      dues: '29.99',
      annual_billing: '12/29/2022',
      address2: 'N/A',
      renewal: '0.00',
      term_ends: 'N/A',
      city_state_zip: 'Carmel, IN 46203',
      expires: 'None',
      initiation: '0.00',
      training_total: 'N/A',
      country: 'United States',
      joined: '11/29/2021',
      balance: '0.00',
      home_phone: 'N/A',
      access: 'Multi Club',
      first_last: '59.98',
      sessions: 'N/A',
      cell_phone: '3172504880',
      home_club: 'WESTFIELD - 146TH ST',
      '6 MO. VIP': 'None',
      tl_sessions: 'N/A',
      emg_phone: 'N/A',
      e_contact: 'N/A',
      rate_id: '1142843',
      phone_barcode: true,
      last_name: 'Barkley',
    },
  ],
  billing_fields: [
    {
      id: 'type',
      description: 'type',
      show: true,
    },
    {
      id: 'next_billing',
      description: 'Next Billing',
      show: true,
    },
    {
      id: 'date',
      description: 'Date',
      show: true,
    },
    {
      id: 'credit_card_num',
      description: 'CC #',
      show: true,
    },
    {
      id: 'billing_cycle',
      description: 'Billing Cycle',
      show: true,
    },
    {
      id: 'credit_card_exp',
      description: 'CC Exp',
      show: true,
    },
    {
      id: 'billing_name',
      description: 'Billing Name',
      show: true,
    },
  ],
  billing_items: [
    {
      type: 'Mastercard',
      date: '7/14/2022',
      next_billing: '8/15/2022',
      billing_cycle: 'Monthly 15th',
      credit_card_num: 'XXXXXXXXXXXX9179',
      credit_card_exp: '6/30/2026',
      billing_name: 'Bryce Hockman',
    },
  ],
  service_fields: [
    {
      id: 'id',
      description: 'ID',
      show: false,
    },
    {
      id: 'amenities',
      description: 'Ameniies',
      show: true,
    },
    {
      id: 'last_billing',
      description: 'Last Billing',
      show: true,
    },
    {
      id: 'current',
      description: 'Current Billing',
      show: true,
    },
  ],
  third: [
    {
      id: 1,
      service: 'fitness',
      dues: 0,
      freeze: 0,
    },
    {
      id: 2,
      service: 'guest priviledges',
      dues: 0,
      freeze: 0,
    },
    {id: 3, service: 'multistate', dues: 0, freeze: 0},
    {id: 4, service: 'group fitness', dues: 0, freeze: 0},
    {
      id: 5,
      service: 'pool whirlpool spa',
      dues: 0,
      freeze: 0,
    },
    {
      id: 6,
      service: 'cycle class',
      dues: 0,
      freeze: 0,
    },
    {id: 7, service: 'la fitness access', dues: 0, freeze: 0},
    {
      id: 8,
      service: 'esporta access',
      dues: 0,
      freeze: 0,
    },
  ],
  items2: [
    {
      id: 1,
      first_name: 'Matias',
      last_name: 'Gauntlett',
      email: 'mgauntlett0@mapquest.com',
      company: 'Fivespan',
      ip_address: '39.139.197.152',
      country_code: 'CN',
    },
    {
      id: 2,
      first_name: 'Laney',
      last_name: 'Veque',
      email: 'lveque1@census.gov',
      company: 'Aimbu',
      ip_address: '77.0.37.83',
      country_code: 'ZM',
    },
    {
      id: 3,
      first_name: 'Fielding',
      last_name: 'Donson',
      email: 'fdonson2@indiatimes.com',
      company: 'Meevee',
      ip_address: '141.126.205.140',
      country_code: 'ID',
    },
    {
      id: 4,
      first_name: 'Ferdinand',
      last_name: 'Bessent',
      email: 'fbessent3@chronoengine.com',
      company: 'Riffpath',
      ip_address: '65.217.64.181',
      country_code: 'FR',
    },
    {
      id: 5,
      first_name: 'Nels',
      last_name: 'Tilt',
      email: 'ntilt4@last.fm',
      company: 'Flashset',
      ip_address: '68.194.140.19',
      country_code: 'JP',
    },
    {
      id: 6,
      first_name: 'Jen',
      last_name: 'Sterrie',
      email: 'jsterrie5@reference.com',
      company: 'Youbridge',
      ip_address: '210.173.199.119',
      country_code: 'VE',
    },
    {
      id: 7,
      first_name: 'Lindsy',
      last_name: 'Kelway',
      email: 'lkelway6@jimdo.com',
      company: 'Rhyloo',
      ip_address: '138.154.16.188',
      country_code: 'CN',
    },
    {
      id: 8,
      first_name: 'Stacy',
      last_name: 'Graeber',
      email: 'sgraeber7@exblog.jp',
      company: 'Dazzlesphere',
      ip_address: '167.47.78.169',
      country_code: 'PH',
    },
    {
      id: 9,
      first_name: 'Sharon',
      last_name: 'Stainland',
      email: 'sstainland8@devhub.com',
      company: 'Browsebug',
      ip_address: '63.59.239.96',
      country_code: 'CN',
    },
    {
      id: 10,
      first_name: 'Caldwell',
      last_name: 'Rimell',
      email: 'crimell9@hexun.com',
      company: 'Rhynyx',
      ip_address: '12.81.190.233',
      country_code: 'PL',
    },
  ],
};
