export const ex = [
  {
    barcode_number: 'F33501281',
    date_of_membership: '',
    first_name: 'celine',
    fitness_type: 'member',
    id: 2,
    last_name: 'Stewart',
    member_photo: 'https://picsum.photos/id/212/200/200',
    membership: 2,
    payment: 'credit card',
    perks: {
      kids: Array(1),
      towel: false,
      racketball: false,
      guestAllowed: false,
      guest: Array(0),
    },
    status: 'DECLINED',
    success: '✅',
    time: '2:58 AM',
    timesheet: (3)[('2:58 AM', '2:58 AM', '2:58 AM')],
  },
  {
    barcode_number: 'F33501217',
    date_of_membership: '',
    first_name: 'john',
    fitness_type: 'member',
    id: 2,
    last_name: 'Stewart',
    member_photo: 'https://picsum.photos/id/212/200/200',
    membership: 2,
    payment: 'credit card',
    perks: {
      kids: Array(1),
      towel: false,
      racketball: false,
      guestAllowed: false,
      guest: Array(0),
    },
    status: 'DECLINED',
    success: '✅',
    time: '2:58 AM',
    timesheet: (3)[('2:58 AM', '2:58 AM', '2:58 AM')],
  },
  {
    barcode_number: 'ccc',
    first_name: 'patrick',
    fitness_type: "member's guest",
    guest_image: 'https://picsum.photos/id/1/200/200',
    id: 1,
    isChecked: true,
    last_name: 'starr',
    phone_number: '920000',
  },
  {
    barcode_number: 'a',
    first_name: 'dfdfs',
    fitness_type: "member's guest",
    guest_image: 'https://picsum.photos/id/2/200/200',
    id: 2,
    isChecked: true,
    last_name: 'manchuri',
    phone_number: '45352',
  },

  {
    barcode_number: 'F33501292',
    date_of_membership: '',
    expiration: 'none',
    first_name: 'Hermoinie',
    fitness_type: 'employee',
    id: 1,
    last_name: 'Granger',
    member_photo: 'https://picsum.photos/id/1027/200',
    membership: 3,
    payment: 'credit card',
    perks: {
      kids: Array(1),
      towel: true,
      racketball: true,
      guestAllowed: true,
      guest: Array(0),
    },
    status: 'OK',
    success: '✅',
    time: '2:58 AM',
    timesheet: (5)[('2:58 AM', '2:58 AM', '2:58 AM', '2:58 AM', '2:58 AM')],
  },
  {
    barcode_number: 'F37221272',
    date_of_membership: '',
    expiration: 'none',
    first_name: 'Yelena',
    fitness_type: 'trainer',
    id: 4,
    last_name: 'Makron',
    member_photo:
      'https://images.unsplash.com/photo-1655857202782-8d0ef8f0254b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2528&q=80',
    membership: 1,
    payment: 'credit card',
    status: 'OK',
    success: '✅',
    time: '2:58 AM',
    timesheet: [Array(2), '2:58 AM', '2:58 AM'],
  },
  {
    id: 0,
    date_of_membership: '',
    barcode_number: 'F33501272',
    first_name: 'Jennifer',
    last_name: 'Lewis',
    payment: 'credit card',
    member_photo: 'https://placekitten.com/200/200',
    fitness_type: 'trainer',
    membership: 3,
    time: 0,
    timesheet: ['🌸'],
    status: 'OK',
    expiration: 'none',
    perks: {
      kids: [false],
      towel: false,
      racketball: false,
      guestAllowed: true,
      guest: [
        {
          first_name: 'dfdfs',
          guest_image: 'https://picsum.photos/id/2/200/200',
          id: 2,
          barcode_number: 'a',
          isChecked: false,
          last_name: 'manchuri',
          fitness_type: "member's guest",
          phone_number: '45352',
        },
        {
          first_name: 'patrick',
          guest_image: 'https://picsum.photos/id/1/200/200',
          id: 1,
          isChecked: true,
          barcode_number: 'ccc',
          last_name: 'starr',
          fitness_type: "member's guest",
          phone_number: '920000',
        },
      ],
    },
  },

  ,
  {
    barcode_number: 'F33501211',
    date_of_membership: '',
    first_name: 'Kelly',
    fitness_type: 'member',
    id: 2,
    last_name: 'Stewart',
    member_photo: 'https://picsum.photos/id/212/200/200',
    membership: 2,
    payment: 'credit card',
    perks: {
      kids: Array(1),
      towel: false,
      racketball: false,
      guestAllowed: false,
      guest: Array(0),
    },
    status: 'DECLINED',
    success: '✅',
    time: '2:58 AM',
    timesheet: (3)[('2:58 AM', '2:58 AM', '2:58 AM')],
  },
];
