export const mock = [
  {
    id: 0,
    date_of_membership: '',
    barcode_number: 'F33501272',
    first_name: 'Jennifer',
    last_name: 'Lewis',
    payment: 'credit card',
    member_photo: 'https://placekitten.com/200/200',
    fitness_type: 'trainer',
    membership: 3,
    time: 0,
    timesheet: [],
    status: 'OK',
    expiration: 'none',
    perks: {
      kids: [false],
      towel: false,
      racketball: false,
      guestAllowed: true,
      guest: [
        {
          first_name: 'dfdfs',
          guest_image: 'https://picsum.photos/id/2/200/200',
          id: 2,
          barcode_number: 'a',
          isChecked: false,
          last_name: 'manchuri',
          fitness_type: "member's guest",
          phone_number: '45352',
        },
        {
          first_name: 'patrick',
          guest_image: 'https://picsum.photos/id/1/200/200',
          id: 1,
          isChecked: true,
          barcode_number: 'ccc',
          last_name: 'starr',
          fitness_type: "member's guest",
          phone_number: '920000',
        },
      ],
    },
  },
  {
    id: 1,
    date_of_membership: '',
    barcode_number: 'F33501292',
    first_name: 'Hermoinie',
    last_name: 'Granger',
    payment: 'credit card',
    member_photo: 'https://picsum.photos/id/1027/200',
    fitness_type: 'employee',
    membership: 3,
    time: 0,
    timesheet: [],
    status: 'OK',
    expiration: 'none',
    perks: {
      kids: [true],
      towel: true,
      racketball: true,
      guestAllowed: true,
      guest: [],
    },
  },
  {
    id: 2,
    date_of_membership: '',
    barcode_number: 'F33501211',
    first_name: 'Kelly',
    last_name: 'Stewart',
    payment: 'credit card',
    member_photo: 'https://picsum.photos/id/212/200/200',
    fitness_type: 'member',
    membership: 2,
    time: 0,
    timesheet: [],
    status: 'DECLINED',
    perks: {
      kids: [false],
      towel: false,
      racketball: false,
      guestAllowed: false,
      guest: [],
    },
  },
  {
    id: 3,
    date_of_membership: '',
    barcode_number: 'F37501272',
    first_name: 'Andrea',
    last_name: 'Boccielli',
    fitness_type: 'fitness',
    payment: 'credit card',
    member_photo: '',
    status: 'OK',
    expiration: 'none',
    time: 0,
    timesheet: [],
    membership: 2,
  },
  {
    id: 4,
    date_of_membership: '',
    barcode_number: 'F37221272',
    first_name: 'Yelena',
    last_name: 'Makron',
    fitness_type: 'trainer',
    payment: 'credit card',
    member_photo:
      'https://images.unsplash.com/photo-1655857202782-8d0ef8f0254b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2528&q=80',
    status: 'OK',
    expiration: 'none',
    time: 0,
    timesheet: [],
    membership: 1,
  },
];

export const health_program = [
  {
    barcode_number: 'EWMFQAVNGLBJ',
    first_name: 'emezie',
    last_name: 'okorafor',
    dob: '',
    zip: 0,
  },
  {
    barcode_number: 'E0U1HNRL4F7O',
    first_name: 'harry',
    last_name: 'okorafor',
    dob: '',
    zip: 0,
  },
  {
    barcode_number: 'DW4CITBSR1HY',
    first_name: 'ron',
    last_name: 'okorafor',
    dob: '',
    zip: 0,
  },
  {
    barcode_number: '6CDXIU0YBHLW',
    first_name: 'malfoy',
    last_name: 'okorafor',
    dob: '',
    zip: 0,
  },
  {
    barcode_number: '6CDXIUDW',
    first_name: 'malfoy',
    last_name: 'okorafor',
    dob: '',
    zip: 0,
  },
];

export const mock2 = [
  {
    id: 0,
    date_of_membership: '',
    barcode_number: 'F33501272',
    first_name: 'Jennifer444',
    last_name: 'Lewis',
    payment: 'credit card',
    member_photo: '🐝',
    fitness_type: 'trainer',
    membership: 3,
    time: 0,
    timesheet: [],
    status: 'OK',
    expiration: 'none',
    perks: {
      kids: [false],
      towel: false,
      racketball: false,
      guest: [true, []],
    },
  },
  {
    id: 1,
    date_of_membership: '',
    barcode_number: 'F37501272',
    first_name: 'Andrea',
    last_name: 'Boccielli',
    fitness_type: 'fitness',
    status: 'OK',
    expiration: 'none',
    membership: 2,
  },
];
